// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pehvdyqtnreuqqlkktif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlaHZkeXF0bnJldXFxbGtrdGlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxODEwNTUsImV4cCI6MjA2ODc1NzA1NX0.6ymGDWiZeAgqVZsXdBYZ1o13rt2Gfiy8wjW93L95MFk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});